import { Institution } from '../src/institutions/institution.entity';
import { User, UserRole, Language } from '../src/users/user.entity';
import { Problem, ProblemCategory, ProblemStatus } from '../src/problems/problem.entity';
import { ProjectTeam, TeamStatus } from '../src/teams/project-team.entity';
import { Milestone, MilestoneStatus } from '../src/teams/milestone.entity';

export const INSTITUTIONS: Partial<Institution>[] = [
  {
    name: 'IIT (ISM) Dhanbad',
    shortName: 'IIT ISM',
    city: 'Dhanbad',
    district: 'Dhanbad',
    departments: [
      'Mining Engineering', 'Civil Engineering', 'Computer Science & Engineering',
      'Electrical Engineering', 'Environmental Engineering', 'Management Studies',
    ],
    researchAreas: ['water', 'mining', 'environment', 'energy', 'civil engineering', 'IoT', 'AI'],
    incubationCells: ['Technology Business Incubator (TBI)', 'Startup Hub ISM'],
    domainTags: ['water', 'mining', 'environment', 'energy', 'civil engineering', 'electronics'],
    problemsResolved: 12,
    problemsActive: 4,
  },
  {
    name: 'Birla Institute of Technology Mesra',
    shortName: 'BIT Mesra',
    city: 'Mesra, Ranchi',
    district: 'Ranchi',
    departments: [
      'Computer Science', 'Electronics & Communication', 'Biotechnology',
      'Pharmaceutical Sciences', 'Architecture', 'Information Technology',
    ],
    researchAreas: ['healthcare', 'biotechnology', 'IT', 'pharmacy', 'architecture', 'AI/ML'],
    incubationCells: ['BIT Mesra Innovation Centre', 'E-Cell'],
    domainTags: ['healthcare', 'biomedical', 'pharma', 'software', 'smart city'],
    problemsResolved: 8,
    problemsActive: 6,
  },
  {
    name: 'National Institute of Technology Jamshedpur',
    shortName: 'NIT Jamshedpur',
    city: 'Jamshedpur',
    district: 'East Singhbhum',
    departments: [
      'Mechanical Engineering', 'Production Engineering', 'Civil Engineering',
      'Computer Science', 'Mathematics', 'Chemistry',
    ],
    researchAreas: ['agriculture', 'manufacturing', 'roads', 'rural tech', 'renewable energy'],
    incubationCells: ['NIT JSR Incubation Centre', 'Rural Technology Centre'],
    domainTags: ['agriculture', 'rural tech', 'manufacturing', 'renewable energy', 'roads'],
    problemsResolved: 6,
    problemsActive: 3,
  },
];

export const SEED_USERS: Partial<User>[] = [
  { name: 'Ramesh Kumar', phone: '9001000001', role: UserRole.CITIZEN, languagePref: Language.HI, isVerified: true },
  { name: 'Sunita Devi', phone: '9001000002', role: UserRole.CITIZEN, languagePref: Language.HI, isVerified: true },
  { name: 'Amit Singh', phone: '9001000003', role: UserRole.CITIZEN, languagePref: Language.EN, isVerified: true },
  { name: 'Dr. Priya Sharma', phone: '9001000004', role: UserRole.FACULTY, languagePref: Language.EN, isVerified: true, orgAffiliation: 'IIT ISM Dhanbad' },
  { name: 'Vikram Pandey', phone: '9001000005', role: UserRole.STUDENT, languagePref: Language.EN, isVerified: true, orgAffiliation: 'IIT ISM Dhanbad' },
  { name: 'Ananya Ghosh', phone: '9001000006', role: UserRole.STUDENT, languagePref: Language.EN, isVerified: true, orgAffiliation: 'BIT Mesra' },
  { name: 'Ravi Tata', phone: '9001000007', role: UserRole.INDUSTRY_PARTNER, languagePref: Language.EN, isVerified: true, orgAffiliation: 'Tata Steel Foundation' },
  { name: 'Admin User', phone: '9000000000', role: UserRole.ADMIN, languagePref: Language.EN, isVerified: true },
];

export const SEED_PROBLEMS = (userIds: string[]): any[] => [
  {
    title: 'Contaminated borewell water in Chandankiyari village',
    description: 'The borewell water in our village has turned yellowish with a strong sulphur smell since March. Over 500 families are affected and children are falling sick. Urgent intervention needed.',
    category: ProblemCategory.WATER,
    district: 'Bokaro',
    village: 'Chandankiyari',
    latitude: 23.769,
    longitude: 86.044,
    status: ProblemStatus.ASSIGNED,
    priorityScore: 78,
    upvotes: 34,
    submittedById: userIds[0],
  },
  {
    title: 'Road to Bagodar completely washed out after monsoon',
    description: 'The 5km road connecting Bagodar town to 12 villages has been washed out. Farmers cannot transport produce, school children walk in dangerous conditions daily.',
    category: ProblemCategory.ROADS,
    district: 'Giridih',
    village: 'Bagodar',
    latitude: 24.178,
    longitude: 85.898,
    status: ProblemStatus.UNDER_REVIEW,
    priorityScore: 65,
    upvotes: 22,
    submittedById: userIds[1],
  },
  {
    title: 'Crop failure due to lack of irrigation in drought-prone area',
    description: 'Three consecutive kharif crop failures in Pakur district due to erratic rainfall and no irrigation infrastructure. Over 200 farmer families are in severe distress.',
    category: ProblemCategory.AGRICULTURE,
    district: 'Pakur',
    latitude: 24.641,
    longitude: 87.844,
    status: ProblemStatus.TEAM_FORMED,
    priorityScore: 82,
    upvotes: 56,
    submittedById: userIds[2],
  },
  {
    title: 'No doctor at Primary Health Centre for 8 months',
    description: 'Jama PHC in Dumka has been without a resident doctor for 8 months. Patients travel 40+ km to Dumka town. Several preventable deaths have been reported.',
    category: ProblemCategory.HEALTHCARE,
    district: 'Dumka',
    latitude: 24.267,
    longitude: 87.248,
    status: ProblemStatus.SUBMITTED,
    priorityScore: 90,
    upvotes: 78,
    submittedById: userIds[0],
  },
  {
    title: 'School in Simdega has no electricity for 3 years',
    description: 'Government Middle School in Bano block has no electricity. 180 students cannot use computers, ceiling fans in summer are non-functional, evening classes impossible.',
    category: ProblemCategory.EDUCATION,
    district: 'Simdega',
    latitude: 22.626,
    longitude: 84.517,
    status: ProblemStatus.PROTOTYPE,
    priorityScore: 60,
    upvotes: 18,
    submittedById: userIds[1],
  },
  {
    title: 'Illegal coal mining causing water table depletion',
    description: 'Illegal rat-hole mining near Jharia has caused the water table to drop 40 feet over 2 years. 15 tube wells have gone dry. Satellite imagery shows 20+ illegal sites.',
    category: ProblemCategory.ENVIRONMENT,
    district: 'Dhanbad',
    latitude: 23.756,
    longitude: 86.414,
    status: ProblemStatus.UNDER_REVIEW,
    priorityScore: 88,
    upvotes: 102,
    submittedById: userIds[2],
  },
  {
    title: 'Digital literacy gap preventing welfare benefit access in Gumla',
    description: 'Over 60% of elderly and women beneficiaries in Gumla cannot access DBT, PM Kisan, and MGNREGA payments online. Local banking correspondents are exploiting this gap.',
    category: ProblemCategory.EDUCATION,
    district: 'Gumla',
    latitude: 23.046,
    longitude: 84.535,
    status: ProblemStatus.ASSIGNED,
    priorityScore: 72,
    upvotes: 44,
    submittedById: userIds[0],
  },
  {
    title: 'Zero livelihood opportunities for tribal youth in Khunti',
    description: 'Tribal youth (18-30) in Khunti have no skill training centres within 50km. 70% migration rate to cities, where they face exploitation. Need vocational training facility.',
    category: ProblemCategory.LIVELIHOOD,
    district: 'Khunti',
    latitude: 23.075,
    longitude: 85.280,
    status: ProblemStatus.SUBMITTED,
    priorityScore: 68,
    upvotes: 29,
    submittedById: userIds[1],
  },
  {
    title: 'Open defecation persists in 40 villages of Latehar despite ODF certification',
    description: 'Despite ODF Plus status on paper, 40+ villages in Latehar block have no functional toilets. Certified toilets are either non-functional or used as storage. Women face safety risks daily.',
    category: ProblemCategory.ENVIRONMENT,
    district: 'Latehar',
    latitude: 23.741,
    longitude: 84.490,
    status: ProblemStatus.PILOTED,
    priorityScore: 75,
    upvotes: 63,
    submittedById: userIds[2],
  },
  {
    title: 'No accessible infrastructure for disabled students in Ranchi colleges',
    description: 'None of the 12 government colleges in Ranchi district have wheelchair ramps, accessible washrooms, or Braille resources. 200+ disabled students are effectively excluded from higher education.',
    category: ProblemCategory.ACCESSIBILITY,
    district: 'Ranchi',
    latitude: 23.344,
    longitude: 85.309,
    status: ProblemStatus.RESOLVED,
    priorityScore: 55,
    upvotes: 41,
    submittedById: userIds[0],
  },
];
